//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saglik_sen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICILAR
    {
        public int KULLANICI_ID { get; set; }
        public string KULLANICI { get; set; }
        public string SIFRE { get; set; }
    }
}
