//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saglik_sen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int ID { get; set; }
        public string TC { get; set; }
        public string ADI { get; set; }
        public string GONDERILEN_SMS { get; set; }
        public System.DateTime GONDERIM_TARIHI { get; set; }
    }
}
