//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saglik_sen.Models
{
    using System;
    using System.Collections.Generic;

    public partial class UYELER
    {
        public int ID { get; set; }
        public string TC { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public int KURUM_ID { get; set; }
        public string TEL { get; set; }
        public DateTime DOGUM_TARIHI { get; set; }
        public string UNVAN { get; set; }
        public short UYELIK_DURUMU { get; set; }

        public virtual Boolean uyelik_durumu2 {get;set;}
    
        public virtual KURUMLAR KURUMLAR { get; set; }
    }
    public class uyelerVM
    {
        public int ID { get; set; }
        public string TC { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string KURUMADI { get; set; }
        public string TEL { get; set; }
        public string DOGUM_TARIHI { get; set; }
        public string UYELIK_DURUMU { get; set; }
        public string UNVAN { get; set; }

    }
}
